include:
  - project: dau/ci/pyci
    file: .gitlab-ci-template.yml

test-3.7:
  extends: .test-3.7

test-3.9:
  extends: .test-3.9

test-3.11:
  extends: .test-3.11

test-3.9-scripts:
  extends: .test-3.9
  script:
    - pip install .
    - |
      for filename in scripts/*;do
        python $filename
      done

build_sdist:
  extends: .build_sdist

test_sdist-3.10:
  extends: .test_sdist-3.10

test_sdist-3.8-win:
  extends: .test_sdist-3.8-win

build_doc:
  extends: .build_doc

pages:
  extends: .pages

assets:
  extends: .assets
