include:
  - project: dau/ci/pyci
    file: .gitlab-ci-template.yml

isort:
  extends: .isort

test-3.8:
  extends: .test-3.8

test-3.12:
  extends: .test-3.12

test-3.9-scripts:
  extends: .test-3.9
  script:
    - pip install .
    - |
      for filename in scripts/*;do
        python $filename
      done

build_sdist:
  extends: .build_sdist

test_sdist-3.8-win:
  extends: .test_sdist-3.8-win

test_sdist-3.12:
  extends: .test_sdist-3.12

build_doc:
  extends: .build_doc

pages:
  extends: .pages

assets:
  extends: .assets

testpypi:
  extends: .testpypi

pypi:
  extends: .pypi
