include:
  - remote: https://gitlab.esrf.fr/workflow/ewoks/ewoksci/raw/main/.gitlab-ci-template.yml

test-3.6:
  extends: .test-3.6
  before_script:
    - !reference [.test-3.6, before_script]
    - pip install git+https://git@gitlab.esrf.fr/workflow/pypushflow.git@main

build_sdist:
  extends: .build_sdist

test_sdist-3.6:
  extends: .test_sdist-3.6
  before_script:
    - !reference [.test-3.6, before_script]
    - pip install git+https://git@gitlab.esrf.fr/workflow/pypushflow.git@main

test_sdist-3.8-win:
  extends: .test_sdist-3.8-win
  before_script:
    - !reference [.test-3.6, before_script]
    - pip install git+https://git@gitlab.esrf.fr/workflow/pypushflow.git@main

build_doc:
  extends: .build_doc

pages:
  extends: .pages

assets:
  extends: .assets
